[package]
name = "vulkan_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
image = "0.25.1"
winit = "0.28.0"

[profile.dev]
opt-level = 1 
